### ISSUE TITLE
Navigating to paths with unicode characters in py27 causes exception

### ISSUE THREAD

**Issue by kennydo** [Yelp/aactivator#18]
When I navigate into a path with unicode in the name, I get the following error:
```
$ cd ~/妹; pwd
/Users/kedo/妹
Traceback (most recent call last):
  File "/usr/local/bin/aactivator.py", line 342, in <module>
    sys.exit(main())
  File "/usr/local/bin/aactivator.py", line 334, in main
    print(aactivator(tuple(sys.argv), os.environ.copy()))
  File "/usr/local/bin/aactivator.py", line 323, in aactivator
    return get_output(env, arg0=args[0])
  File "/usr/local/bin/aactivator.py", line 304, in get_output
    activate_path = config.find_allowed(pwd)
  File "/usr/local/bin/aactivator.py", line 221, in find_allowed
    return first(search_parent_paths(path), self.is_allowed)
  File "/usr/local/bin/aactivator.py", line 89, in first
    if predicate(x):
  File "/usr/local/bin/aactivator.py", line 224, in is_allowed
    activate = os.path.join(path, ACTIVATE)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 12: ordinal not in range(128)
```

I tried to get a branch working to support unicode, but making code + tests compatible with both py2 and py3 without requiring third party libraries caused great anguishment.

To anyone else facing this issue, changing first line from `#!/usr/bin/env python2.7` to `#!/usr/bin/env python3.5` made unicode work perfectly.

**Comment by asottile** [comment]
I'll switch the default to python3 (as it probably should be anyway).

I think the rest can be solved by using bytes throughout (since filepaths aren't necessarily guaranteed to be UTF-8 afaik)

**Comment by asottile** [comment]
We should still fix this for python2 eventually however.

Curious: which third party library were you reaching for?

**Comment by asottile** [comment]
via #19, python 3 is now the default

**Comment by kennydo** [comment]
Thanks for the fix!

I was going to use `future`, but quickly gave up on that approach.

**Comment by asottile** [comment]
Ah, we still want this issue since it's still broken in py27.

We've also moved to [discourage python-future](https://github.com/Yelp/yelp_clog/pull/18#issue-143837308) (perhaps you'll find this writeup useful as well)

**Comment by asottile** [comment]
the effort to fix this is too high and python2.x will die within the year anyway. closing this as wontfix
