### ISSUE TITLE
Question: how does aactivator compare with direnv?

### ISSUE THREAD

**Issue by pmav99** [Yelp/aactivator#29]
I think that the most prominent project with similar goals/functionality is [direnv](https://github.com/direnv/direnv), but it isn't mentioned in the alternatives section in the README. Are there any security/functionality problems with direnv?

**Comment by asottile** [comment]
here's the checklist from features that aactivatorr gives, but for direnv:

- [x] asks permission before sourcing
- [x] remembers what you've given permission for
- [x] doesn't override `cd` builtin
- [x] supports zsh
- [ ] will not source things other users could write

so yes, seems to be missing the security features aactivator mentions:

```console
$ eval "$(~/go/bin/direnv hook bash)"
$ type cd
cd is a shell builtin
$ echo "$PROMPT_COMMAND"
_direnv_hook;eval "`/home/asottile/opt/venv/bin/aactivator`"; if [ -d .git -a ! -x .git/hooks/pre-commit -a -e .pre-commit-config.yaml ] && which pre-commit >& /dev/null; then pre-commit install; fi; 
$ mkdir /tmp/foo
$ chmod 777 /tmp/foo
$ echo 'export FOO=1' > /tmp/foo/.envrc
$ ~/go/bin/direnv allow /tmp/foo/
$ cd /tmp/foo/
direnv: loading .envrc
direnv: export +FOO
```

**Comment by pmav99** [comment]
Thank you for the timely response :)

TBH though, I believe that direnv stores the hash of the file. As a result, even if your own user makes a change in `.envrc` you need to explicitly run `direnv allow`. The permissions of the files with the hashes are user-only writable: 
```
ls -lah  ~/.config/direnv/allow/
```

**Comment by asottile** [comment]
even if that is how it works, one could imagine a malicious actor who wrote the file just before `direnv allow ...` is called (and after the user had manually inspected that file)

this scenario doesn't exist for aactivator

**Comment by asottile** [comment]
here's the play-by-play of that scenario:

```console
$ cat /tmp/foo/.envrc 
FOO=1
$ echo looks good to me'!'
looks good to me!
$ # simulate a malicious actor
$ sudo -u nobody bash -c 'echo "export FOO=haxxed" > /tmp/.envrc && mv -f /tmp/.envrc /tmp/foo'
$ ~/go/bin/direnv allow /tmp/foo/
$ cd /tmp/foo/
direnv: loading .envrc
direnv: export +FOO
$ echo $FOO
haxxed
```

**Comment by pmav99** [comment]
Thank you @asottile
