### ISSUE TITLE
Aactivator doesn't work for ZSH

### ISSUE THREAD

**Issue by vunhatchuong123** [Yelp/aactivator#41]
Setup:

- zsh 5.9 (x86_64-pc-linux-gnu)
- EndeavourOS
- Installation via pip

Problem:

`.activate.sh` doesn't activate.

**Comment by asottile** [comment]
can you show full reproduction steps? it works fine for me and is tested against zsh (I suspect you haven't set it up properly)

**Comment by vunhatchuong123** [comment]
Step 1:

Install with `pip install aactivator`

Step 2:

Put `eval "$(aactivator init)"` in `.zshrc` which for me located inside `~/.config/zsh/`

Step 3:

- Tried symlink with `ln -s venv/bin/activate .activate.sh` for venv.
- Or a new `.activate.sh` with `hi="hello"`, `echo $hi` doesn't work.

**Comment by asottile** [comment]
did you open a new shell? did something crash? was there output?

**Comment by vunhatchuong123** [comment]
I did open a new shell, nothing crash, no output. 
I'm able to use `aactivate init` which output: 
```bash
export AACTIVATOR_VERSION=1.0.1
alias aactivator=/home/ronny/.local/bin/aactivator
unset AACTIVATOR_ACTIVE
if [ "$ZSH_VERSION" ]; then
    precmd_aactivator() { if [ -x /home/ronny/.local/bin/aactivator ]; then  eval "`/home/ronny/.local/bin/aactivator`"; fi; }
    if ! [ "${precmd_functions[(r)precmd_aactivator]}" ]; then
        precmd_functions=(precmd_aactivator $precmd_functions)
    fi
else
    if ! ( echo "$PROMPT_COMMAND" | grep -Fq 'if [ -x /home/ronny/.local/bin/aactivator ]; then  eval "`/home/ronny/.local/bin/aactivator`"; fi' ); then
        PROMPT_COMMAND='if [ -x /home/ronny/.local/bin/aactivator ]; then  eval "`/home/ronny/.local/bin/aactivator`"; fi; '"$PROMPT_COMMAND"
    fi
fi
```

**Comment by asottile** [comment]
does it work if you run the command you put in your rcfile directly?

**Comment by vunhatchuong123** [comment]
If you mean does typing `hi="hello"` in terminal works. Yes it does, I can echo it.

**Comment by asottile** [comment]
no, the `eval` line, and then aactivator

**Comment by vunhatchuong123** [comment]
No it doesn't work.

**Comment by asottile** [comment]
"it doesn't work" does not help me help you

**Comment by vunhatchuong123** [comment]
Ok, If you mean does typing `eval "$(aactivator init)"` and then `.activate.sh` works or not, it doesn't.

**Comment by asottile** [comment]
I can't see your screen. you need to communicate in detail exactly what you're doing and what you're seeing and what you expect

**Comment by vunhatchuong123** [comment]
Apparently it doesn't work on my mounted HDD using fstab or anywhere else other than $HOME.

`/etc/fstab`:

```bash
UUID=<UUID>	/mnt/HDD	ntfs	defaults,exec	0	2
```

Works fine with both bash and zsh.

**Comment by asottile** [comment]
usually it will tell you that it is refusing to source a file -- and why -- was it saying that and you just decided it wasn't important information to share?

**Comment by vunhatchuong123** [comment]
It just doesn't display anything.
![image](https://user-images.githubusercontent.com/20581504/216511736-83cf9fb6-6c13-4cb0-a9a4-5835f10cf369.png)

**Comment by asottile** [comment]
and you have both an `.activate.sh` and `.deactivate.sh` ? -- does `aactivator security-check .activate.sh` show anything?

**Comment by vunhatchuong123** [comment]
It does check when run in $HOME only, not when in /mnt/. NOTHING happens when run in /mnt/

**Comment by asottile** [comment]
ok I'm tired of you not actually answering my questions or even putting in the basic effort to be helpful.  please [watch this](https://youtu.be/ritp4gAqNMI) and try to do better

**Comment by vunhatchuong123** [comment]
Didn't realize `aactivator security-check .activate.sh` is a command, that's my bad. I solved my problem.

But half of the conversion is just you thought I hide some error/output.

> usually it will tell you that it is refusing to source a file -- and why -- was it saying that and you just decided it wasn't important information to share?"

When there's nothing that appear on my screen, that's why I wasn't saying anything.  Sure I could've said "nothing appear" but you also should do a better job of asking questions.
