### ISSUE TITLE
ability to source `.activate.sh` even if writeable by group ("Cowardly refusing to source .activate.sh because writeable by others")

### ISSUE THREAD

**Issue by FelixSchwarz** [Yelp/aactivator#48]
Currently aactivator will not source any script that is "writeable by others": https://github.com/Yelp/aactivator/blob/6a6ac54e411715f5d6cdb113c1a85a8ac6ef04f1/aactivator.py#L81

In my case the files are just writeable by me and group members but not "others". While I can see that you really want to have tight restrictions in some places, I'm willing to accept group writeable files and directories.

It would be nice if there was an option to loosen the restriction a bit.

**Comment by asottile** [comment]
group members are "others" -- it would allow any group member to perform arbitrary code execution

**Comment by asottile** [comment]
you're free to run an insecure fork but we will not be loosening the security of this tool
