### ISSUE TITLE
Checks for group permission despise not mentioned in the docs

### ISSUE THREAD

**Issue by Stubatiger** [Yelp/aactivator#49]
Hey im trying to use aactivator with zsh on ubuntu 22.04

I setup a venv in my project with `virtualenv venv` and then created a symlink with `ln -s venv/bin/activate .activate.sh`

But aactivator is then telling me that its cowardly refusing to source .activate.sh because it is writable by others.
But permissions of venv/bin/activate are `0664`

In the code here https://github.com/Yelp/aactivator/blob/6a6ac54e411715f5d6cdb113c1a85a8ac6ef04f1/aactivator.py#L81 the security checks not only for write permissions of others (stat.S_IWOTH) but also if the group can write (stat.S_IWGRP).

This is not mentioned in the docs and also the error message is misleading.

Is this intended? Or am i just not seeing something?

I followed the steps shown here https://youtu.be/q8DkatMZvUs?t=1519

**Comment by asottile** [comment]
people in a group are _other_ people
